(function () {
  const categories = {
    characters: "Characters",
    worlds: "Worlds & Places",
    vehicles: "Starships & Vehicles",
    stories: "Films & Moments",
    force: "Force & Orders",
    species: "Droids & Species"
  };

  const rows = [
    ["characters", "easy", "Luke Skywalker", "Which character grows up on Tatooine before becoming a Jedi who confronts Darth Vader?", ["Luke Skywalker", "Wedge Antilles", "Biggs Darklighter", "Poe Dameron"], 0, "Luke begins as a moisture farmer on Tatooine and becomes central to the Jedi's return."],
    ["characters", "easy", "Leia Organa", "Which Alderaanian princess becomes a general in the Resistance?", ["Padme Amidala", "Leia Organa", "Mon Mothma", "Hera Syndulla"], 1, "Leia Organa is princess of Alderaan, a Rebel leader, and later a Resistance general."],
    ["characters", "easy", "Han Solo", "Who pilots the Millennium Falcon alongside Chewbacca through much of the original trilogy?", ["Lando Calrissian", "Han Solo", "Wedge Antilles", "Cassian Andor"], 1, "Han Solo is the smuggler captain most associated with the Falcon."],
    ["characters", "easy", "Darth Vader", "Which Sith Lord is revealed to have once been Anakin Skywalker?", ["Darth Maul", "Darth Vader", "Count Dooku", "Darth Bane"], 1, "Darth Vader is the fallen identity of Anakin Skywalker."],
    ["characters", "easy", "Obi-Wan Kenobi", "Which Jedi trains Anakin Skywalker and later watches over Luke on Tatooine?", ["Ki-Adi-Mundi", "Obi-Wan Kenobi", "Plo Koon", "Kit Fisto"], 1, "Obi-Wan mentors Anakin, survives Order 66, and protects Luke from afar."],
    ["characters", "easy", "Yoda", "Which ancient Jedi Master trains Luke on Dagobah?", ["Yoda", "Mace Windu", "Qui-Gon Jinn", "Ezra Bridger"], 0, "Yoda goes into exile on Dagobah and teaches Luke the Jedi path."],
    ["characters", "medium", "Ahsoka Tano", "Which former Padawan of Anakin Skywalker leaves the Jedi Order during the Clone Wars?", ["Barriss Offee", "Ahsoka Tano", "Shaak Ti", "Asajj Ventress"], 1, "Ahsoka Tano walks away from the Jedi after being falsely accused and losing faith in the Order."],
    ["characters", "medium", "Rey Skywalker", "Which scavenger from Jakku trains with Luke and Leia before confronting Palpatine on Exegol?", ["Jyn Erso", "Rey", "Qi'ra", "Sabine Wren"], 1, "Rey is introduced as a Jakku scavenger and becomes the central Jedi figure of the sequel trilogy."],
    ["characters", "easy", "Kylo Ren", "Which dark side warrior is born Ben Solo?", ["Kylo Ren", "Snoke", "General Hux", "Darth Plagueis"], 0, "Kylo Ren is Ben Solo, son of Leia Organa and Han Solo."],
    ["characters", "medium", "Din Djarin", "Which Mandalorian bounty hunter becomes Grogu's guardian?", ["Boba Fett", "Din Djarin", "Pre Vizsla", "Jango Fett"], 1, "Din Djarin protects Grogu and becomes a father figure to him."],
    ["characters", "easy", "Grogu", "Which Force-sensitive foundling is often protected by Din Djarin?", ["Grogu", "Omega", "Wicket", "Nien Nunb"], 0, "Grogu is the young Force-sensitive foundling at the heart of The Mandalorian."],
    ["characters", "medium", "Boba Fett", "Which armored bounty hunter survives the Sarlacc and later claims Jabba's palace?", ["Jango Fett", "Boba Fett", "Dengar", "Bossk"], 1, "Boba Fett escapes the Sarlacc and later takes control of Jabba's former territory."],
    ["characters", "easy", "Lando Calrissian", "Who runs Cloud City before helping the Rebellion at Endor?", ["Lando Calrissian", "Bail Organa", "Saw Gerrera", "DJ"], 0, "Lando is Cloud City's administrator and later a Rebel general."],
    ["characters", "easy", "Darth Sidious", "Which Sith Lord engineers the fall of the Republic while serving as Palpatine?", ["Darth Sidious", "Darth Malak", "Darth Nihilus", "Darth Talon"], 0, "Darth Sidious manipulates the Clone Wars and transforms the Republic into the Empire."],
    ["characters", "easy", "Padme Amidala", "Which Naboo leader is queen during the invasion of Naboo and later a senator?", ["Satine Kryze", "Padme Amidala", "Breha Organa", "Mon Mothma"], 1, "Padme Amidala serves as queen of Naboo and later as a senator."],
    ["characters", "easy", "Anakin Skywalker", "Which Jedi Knight is prophesied as the Chosen One before falling to the dark side?", ["Anakin Skywalker", "Kanan Jarrus", "Cal Kestis", "Quinlan Vos"], 0, "Anakin is believed by many Jedi to be the Chosen One, but he becomes Darth Vader."],
    ["characters", "medium", "Mace Windu", "Which Jedi Master is known for a purple lightsaber and membership on the High Council?", ["Mace Windu", "Saesee Tiin", "Adi Gallia", "Depa Billaba"], 0, "Mace Windu is a senior Jedi Council member recognized for his purple blade."],
    ["characters", "medium", "Qui-Gon Jinn", "Which Jedi discovers Anakin on Tatooine and believes he is the Chosen One?", ["Qui-Gon Jinn", "Obi-Wan Kenobi", "Yarael Poof", "Coleman Trebor"], 0, "Qui-Gon finds Anakin and argues for his Jedi training."],
    ["characters", "medium", "Count Dooku", "Which former Jedi becomes Darth Tyranus and leads the Separatists?", ["Count Dooku", "Savage Opress", "Mas Amedda", "Sifo-Dyas"], 0, "Count Dooku leaves the Jedi Order, becomes Darth Tyranus, and leads the Separatist movement."],
    ["characters", "hard", "Grand Admiral Thrawn", "Which Chiss strategist becomes a Grand Admiral known for studying an enemy's art?", ["Grand Admiral Thrawn", "Firmus Piett", "Orson Krennic", "Rae Sloane"], 0, "Thrawn is famous for tactical brilliance and cultural analysis."],

    ["worlds", "easy", "Tatooine", "Which desert world is home to Mos Eisley, Jabba's palace, and the Lars homestead?", ["Jakku", "Tatooine", "Geonosis", "Jedha"], 1, "Tatooine is the Outer Rim desert planet central to many Skywalker family events."],
    ["worlds", "easy", "Coruscant", "Which city-covered planet houses the Galactic Senate and Jedi Temple during the prequel era?", ["Coruscant", "Corellia", "Hosnian Prime", "Chandrila"], 0, "Coruscant is the galactic capital and seat of the Senate for much of the Republic era."],
    ["worlds", "easy", "Hoth", "Which ice world hosts the Rebel Alliance's Echo Base?", ["Ilum", "Hoth", "Mygeeto", "Kijimi"], 1, "Echo Base is hidden on Hoth at the start of The Empire Strikes Back."],
    ["worlds", "easy", "Endor", "Which forest moon is home to Ewoks and the shield generator for the second Death Star?", ["Endor", "Yavin 4", "Kashyyyk", "Dantooine"], 0, "The Endor moon is where Rebels and Ewoks attack the Imperial shield bunker."],
    ["worlds", "easy", "Dagobah", "On which swamp planet does Yoda train Luke?", ["Dagobah", "Felucia", "Dathomir", "Rodia"], 0, "Yoda hides on Dagobah after the Jedi purge."],
    ["worlds", "easy", "Naboo", "Which planet is represented by Queen Amidala and has both human and Gungan societies?", ["Naboo", "Alderaan", "Chandrila", "Ryloth"], 0, "Naboo is home to humans, Gungans, and Queen Amidala's government."],
    ["worlds", "easy", "Mustafar", "On which volcanic planet do Obi-Wan and Anakin duel at the end of Revenge of the Sith?", ["Mustafar", "Sullust", "Lava Minor", "Kessel"], 0, "Mustafar is the fiery world where Anakin is defeated and transformed into Vader."],
    ["worlds", "medium", "Kamino", "Which ocean planet secretly creates the clone army for the Republic?", ["Kamino", "Mon Cala", "Manaan", "Scarif"], 0, "Kamino's cloners produce the Grand Army of the Republic."],
    ["worlds", "medium", "Geonosis", "Which rocky world hosts the arena battle that begins the Clone Wars?", ["Geonosis", "Utapau", "Cato Neimoidia", "Saleucami"], 0, "The Battle of Geonosis marks the first major battle of the Clone Wars."],
    ["worlds", "easy", "Jakku", "Which desert planet is Rey's home when The Force Awakens begins?", ["Tatooine", "Jakku", "Pasaana", "Jedha"], 1, "Rey scavenges wreckage on Jakku before joining the Resistance story."],
    ["worlds", "medium", "Scarif", "Which tropical Imperial archive world is attacked by Rogue One?", ["Scarif", "Lah'mu", "Niamos", "Eadu"], 0, "Scarif stores the Death Star plans in an Imperial Citadel tower."],
    ["worlds", "easy", "Alderaan", "Which peaceful Core World is destroyed by the first Death Star?", ["Alderaan", "Chandrila", "Corellia", "Hosnian Prime"], 0, "Alderaan is destroyed as a demonstration of the Death Star's power."],
    ["worlds", "easy", "Bespin", "Which gas giant is the location of Cloud City?", ["Bespin", "Yavin", "D'Qar", "Polis Massa"], 0, "Cloud City floats in Bespin's atmosphere."],
    ["worlds", "easy", "Kashyyyk", "Which forested world is the homeworld of the Wookiees?", ["Kashyyyk", "Endor", "Takodana", "Onderon"], 0, "Kashyyyk is the Wookiee homeworld."],
    ["worlds", "medium", "Mandalore", "Which world is central to Mandalorian culture and the Darksaber's legacy?", ["Concord Dawn", "Mandalore", "Krownest", "Nevarro"], 1, "Mandalore is the ancestral world tied to Mandalorian clans and leadership."],
    ["worlds", "medium", "Lothal", "Which Outer Rim world is protected by the crew of the Ghost in Rebels?", ["Lothal", "Atollon", "Garel", "Jelucan"], 0, "Lothal is a major setting for Star Wars Rebels."],
    ["worlds", "medium", "Exegol", "Which hidden Sith world is Palpatine's stronghold in The Rise of Skywalker?", ["Exegol", "Moraband", "Malachor", "Ziost"], 0, "Exegol is the secret Sith world where Palpatine gathers the Final Order."],
    ["worlds", "medium", "Jedha", "Which moon is a spiritual center connected to kyber crystals in Rogue One?", ["Jedha", "Ilum", "Ahch-To", "Bogano"], 0, "Jedha is sacred to many Force traditions and tied to kyber mining."],
    ["worlds", "easy", "Crait", "Which salt-covered world is the site of the Resistance's final stand in The Last Jedi?", ["Crait", "Kef Bir", "D'Qar", "Pasaana"], 0, "Crait's white salt flats reveal red mineral beneath during the battle."],
    ["worlds", "medium", "Ahch-To", "On which ocean world does Luke Skywalker live in exile near the first Jedi Temple?", ["Ahch-To", "Tython", "Ossus", "Lothal"], 0, "Luke retreats to Ahch-To, a world associated with early Jedi history."],

    ["vehicles", "easy", "Millennium Falcon", "Which modified YT-1300 freighter completes the Kessel Run in Han Solo's legend?", ["Millennium Falcon", "Ghost", "Outrider", "Razor Crest"], 0, "The Millennium Falcon is Han and Chewie's famed freighter."],
    ["vehicles", "easy", "Death Star", "Which moon-sized Imperial battle station can destroy planets?", ["Starkiller Base", "Death Star", "Executor", "Citadel Tower"], 1, "The Death Star is the Empire's planet-destroying superweapon."],
    ["vehicles", "easy", "Star Destroyer", "Which wedge-shaped capital ships are visual symbols of Imperial power?", ["Star Destroyers", "Nebulon-B frigates", "Hammerhead corvettes", "Lucrehulk carriers"], 0, "Imperial Star Destroyers project the Empire's military dominance."],
    ["vehicles", "easy", "X-wing starfighter", "Which Rebel starfighter opens its S-foils into attack position?", ["A-wing", "X-wing", "V-wing", "N-1 starfighter"], 1, "X-wings split their wings into the distinctive X shape for combat."],
    ["vehicles", "easy", "TIE fighter", "Which Imperial starfighter is named for its twin ion engines?", ["TIE fighter", "Vulture droid", "ARC-170", "U-wing"], 0, "TIE fighters are fast Imperial craft with twin ion engines."],
    ["vehicles", "medium", "Slave I", "Which Firespray-class ship is associated with Jango and Boba Fett?", ["Slave I", "Razor Crest", "Hound's Tooth", "Punishing One"], 0, "Slave I is the distinctive Firespray craft flown by Jango and Boba Fett."],
    ["vehicles", "medium", "Razor Crest", "What is Din Djarin's original gunship in The Mandalorian?", ["Razor Crest", "Gauntlet", "Fondor Haulcraft", "Ghost"], 0, "The Razor Crest is Din Djarin's first main ship in the series."],
    ["vehicles", "medium", "Executor", "What is Darth Vader's massive Super Star Destroyer called?", ["Executor", "Devastator", "Finalizer", "Chimaera"], 0, "Executor is Vader's flagship during the original trilogy."],
    ["vehicles", "easy", "Tantive IV", "Which blockade runner carries Leia and the Death Star plans at the start of A New Hope?", ["Tantive IV", "Home One", "Raddus", "Profundity"], 0, "The Tantive IV is the Rebel blockade runner boarded by Vader."],
    ["vehicles", "medium", "N-1 starfighter", "Which sleek Naboo fighter type is later rebuilt by Din Djarin?", ["N-1 starfighter", "Z-95 Headhunter", "TIE Defender", "Delta-7 Aethersprite"], 0, "Din Djarin modifies a Naboo N-1 starfighter after losing the Razor Crest."],
    ["vehicles", "medium", "Naboo royal starship", "Which polished diplomatic vessel carries Queen Amidala away from Naboo?", ["Naboo royal starship", "Solar sailer", "Radiant VII", "Tantive IV"], 0, "The Naboo royal starship is the chrome vessel used during the Naboo crisis."],
    ["vehicles", "medium", "Eta-2 Actis-class light interceptor", "Which compact Jedi interceptor type is used by Anakin and Obi-Wan over Coruscant?", ["Eta-2 Actis-class", "T-65 X-wing", "TIE Advanced x1", "A/SF-01 B-wing"], 0, "Eta-2 Actis-class interceptors appear in the Battle of Coruscant."],
    ["vehicles", "medium", "A-wing interceptor", "Which Rebel interceptor is especially fast and helps at the Battle of Endor?", ["A-wing", "Y-wing", "U-wing", "V-wing"], 0, "A-wings are fast Rebel interceptors used in the fleet battle over Endor."],
    ["vehicles", "medium", "B-wing starfighter", "Which Rebel starfighter is designed as a heavy assault craft with a rotating cockpit?", ["B-wing", "A-wing", "N-1", "TIE Bomber"], 0, "The B-wing is a heavy assault starfighter in the Rebel arsenal."],
    ["vehicles", "easy", "Y-wing starfighter", "Which Rebel craft is widely used as a bomber and attack starfighter?", ["Y-wing", "Naboo N-1", "TIE Interceptor", "Vulture droid"], 0, "Y-wings serve as rugged Rebel bombers and attack craft."],
    ["vehicles", "easy", "All Terrain Armored Transport", "Which towering Imperial walkers assault Echo Base on Hoth?", ["AT-ATs", "AT-RTs", "AT-TEs", "SPHA-Ts"], 0, "AT-AT walkers lead the Empire's ground assault on Hoth."],
    ["vehicles", "easy", "All Terrain Scout Transport", "Which two-legged Imperial scout walkers fight at Endor?", ["AT-STs", "AT-ATs", "Juggernauts", "MTT carriers"], 0, "AT-ST walkers patrol Endor and support Imperial troops."],
    ["vehicles", "easy", "Speeder bike", "Which fast repulsorlift vehicle is used in the Endor forest chase?", ["Speeder bike", "Podracer", "BARC speeder", "Swoop bike"], 0, "Speeder bikes race through the trees in Return of the Jedi."],
    ["vehicles", "medium", "Lambda-class T-4a shuttle", "Which tri-wing Imperial shuttle carries the strike team toward Endor?", ["Lambda-class shuttle", "U-wing", "TIE Reaper", "Sheathipede shuttle"], 0, "A stolen Lambda-class shuttle is used to approach Endor."],
    ["vehicles", "hard", "MC80 Star Cruiser", "Which Mon Calamari capital ship type includes Home One?", ["MC80 Star Cruiser", "Dreadnought-class cruiser", "Quasar Fire carrier", "Munificent frigate"], 0, "Home One is an MC80 Star Cruiser used by the Rebel Alliance."],

    ["stories", "easy", "Star Wars: Episode IV A New Hope", "In A New Hope, who destroys the first Death Star?", ["Han Solo", "Luke Skywalker", "Wedge Antilles", "Leia Organa"], 1, "Luke fires the decisive proton torpedoes into the exhaust port."],
    ["stories", "easy", "Star Wars: Episode V The Empire Strikes Back", "In The Empire Strikes Back, what family truth does Vader reveal to Luke?", ["Vader is Luke's father", "Leia is Vader's apprentice", "Yoda built the Death Star", "Han is a Jedi"], 0, "Vader reveals that he is Luke's father during their duel on Cloud City."],
    ["stories", "easy", "Star Wars: Episode VI Return of the Jedi", "Where does Luke face Vader and the Emperor during Return of the Jedi's climax?", ["Death Star II", "Cloud City", "Jabba's palace", "Yavin 4"], 0, "Luke confronts them aboard the second Death Star."],
    ["stories", "easy", "Star Wars: Episode I The Phantom Menace", "In The Phantom Menace, which planet is invaded by the Trade Federation?", ["Naboo", "Alderaan", "Kashyyyk", "Ryloth"], 0, "The Trade Federation blockade and invasion target Naboo."],
    ["stories", "medium", "Star Wars: Episode II Attack of the Clones", "Which battle at the end of Attack of the Clones launches the Clone Wars?", ["Battle of Geonosis", "Battle of Coruscant", "Battle of Scarif", "Battle of Yavin"], 0, "The first major clash of clones, Jedi, and Separatists erupts on Geonosis."],
    ["stories", "easy", "Star Wars: Episode III Revenge of the Sith", "Which command causes clone troopers to turn on the Jedi in Revenge of the Sith?", ["Order 37", "Order 66", "Base Delta Zero", "Contingency Cinder"], 1, "Order 66 identifies Jedi as traitors and triggers the purge."],
    ["stories", "easy", "Star Wars: Episode VII The Force Awakens", "What First Order superweapon threatens the New Republic in The Force Awakens?", ["Starkiller Base", "Death Star II", "World Devastator", "Malevolence"], 0, "Starkiller Base is the First Order's planet-scale superweapon."],
    ["stories", "easy", "Star Wars: Episode VIII The Last Jedi", "Which world hosts the Resistance's final stand in The Last Jedi?", ["Crait", "D'Qar", "Ahch-To", "Kef Bir"], 0, "The Resistance retreats to an old base on Crait."],
    ["stories", "medium", "Star Wars: Episode IX The Rise of Skywalker", "Which hidden Sith world is central to The Rise of Skywalker's final conflict?", ["Exegol", "Malachor", "Moraband", "Dromund Kaas"], 0, "The Resistance attacks Palpatine's forces at Exegol."],
    ["stories", "easy", "Rogue One: A Star Wars Story", "What does the Rogue One team steal from Scarif?", ["Death Star plans", "A Sith holocron", "The Darksaber", "Clone army records"], 0, "Rogue One transmits the Death Star plans to the Rebellion."],
    ["stories", "medium", "Solo: A Star Wars Story", "In Solo, which ship does Han eventually win from Lando?", ["Millennium Falcon", "Tantive IV", "Razor Crest", "Ghost"], 0, "Han wins the Falcon from Lando Calrissian."],
    ["stories", "easy", "The Mandalorian", "In The Mandalorian, which foundling changes Din Djarin's path?", ["Grogu", "Omega", "Ezra Bridger", "Babu Frik"], 0, "Protecting Grogu pulls Din away from ordinary bounty work."],
    ["stories", "medium", "Ahsoka (television series)", "Which Imperial strategist's return is a major threat in Ahsoka?", ["Grand Admiral Thrawn", "Grand Moff Tarkin", "Admiral Ozzel", "Orson Krennic"], 0, "Ahsoka centers heavily on the danger of Thrawn's return."],
    ["stories", "medium", "Andor (television series)", "Which Rebel intelligence figure is the main character of Andor?", ["Cassian Andor", "Bodhi Rook", "Biggs Darklighter", "Galen Erso"], 0, "Andor follows Cassian's path into the early Rebellion."],
    ["stories", "medium", "Star Wars Rebels", "What is the name of the starship used by Hera Syndulla's rebel cell?", ["Ghost", "Phantom Menace", "Fondor", "Marauder"], 0, "The Ghost is the main ship of the Rebels crew."],
    ["stories", "easy", "Star Wars: The Clone Wars", "Which galactic conflict is the focus of The Clone Wars animated series?", ["Clone Wars", "Yuuzhan Vong War", "Galactic Civil War", "Mandalorian Wars"], 0, "The Clone Wars series explores the war between the Republic and Separatists."],
    ["stories", "easy", "Princess Leia Organa", "Who hides the Death Star plans in R2-D2 at the start of A New Hope?", ["Leia Organa", "Mon Mothma", "Padme Amidala", "Jyn Erso"], 0, "Leia entrusts the plans to R2-D2 while under attack."],
    ["stories", "easy", "Hoth", "The Empire Strikes Back opens with the Rebellion hiding on which planet?", ["Hoth", "Dagobah", "Bespin", "Tatooine"], 0, "The Rebels begin the film at Echo Base on Hoth."],
    ["stories", "easy", "Jabba Desilijic Tiure", "In Return of the Jedi, the heroes rescue Han from which crime lord?", ["Jabba the Hutt", "Dryden Vos", "Prince Xizor", "Cad Bane"], 0, "Han is freed from Jabba's palace on Tatooine."],
    ["stories", "medium", "Darth Maul", "Which Sith apprentice duels Qui-Gon and Obi-Wan on Naboo?", ["Darth Maul", "Count Dooku", "Savage Opress", "Darth Sidious"], 0, "Darth Maul fights the Jedi during the Battle of Naboo."],

    ["force", "easy", "The Force", "What mystical energy field binds the galaxy together in Star Wars?", ["The Force", "Hyperdrive", "Beskar", "Coaxium"], 0, "The Force is the energy field sensed and used by Force-sensitive beings."],
    ["force", "easy", "Jedi Order", "Which ancient order serves the light side as guardians of peace and justice?", ["Jedi Order", "Sith Eternal", "Bounty Hunters' Guild", "Trade Federation"], 0, "The Jedi Order trains Force-users and protects the Republic."],
    ["force", "easy", "Sith", "Which dark side tradition opposes the Jedi across many eras?", ["Sith", "Gungans", "Chiss Ascendancy", "Mon Calamari"], 0, "The Sith seek power through the dark side and repeatedly clash with the Jedi."],
    ["force", "medium", "Rule of Two", "What Sith doctrine limits the order to one master and one apprentice?", ["Rule of Two", "Chosen One prophecy", "Way of the Mandalore", "Jedi Code"], 0, "The Rule of Two preserves Sith secrecy through a master-apprentice lineage."],
    ["force", "easy", "Lightsaber", "What elegant weapon is most closely associated with Jedi and Sith?", ["Lightsaber", "Bowcaster", "Vibro-ax", "Gaderffii stick"], 0, "Lightsabers are the iconic plasma-bladed weapons of Force traditions."],
    ["force", "medium", "Kyber crystal", "What type of crystal focuses a lightsaber blade and powers superweapons like the Death Star?", ["Kyber crystal", "Coaxium", "Beskar", "Durasteel"], 0, "Kyber crystals focus lightsabers and are exploited by Imperial weapons programs."],
    ["force", "easy", "Jedi Temple", "Where is the Jedi Order's main temple located during the final years of the Republic?", ["Coruscant", "Tatooine", "Ahch-To", "Naboo"], 0, "The Jedi Temple stands on Coruscant during the prequel era."],
    ["force", "medium", "Clone trooper", "Who forms the Grand Army of the Republic during the Clone Wars?", ["Clone troopers", "Stormtroopers", "Battle droids", "Death troopers"], 0, "Clone troopers are created on Kamino for the Republic."],
    ["force", "easy", "Order 66", "Which secret order brands Jedi as traitors to the Republic?", ["Order 66", "Rule of Two", "Code Cylinder", "Project Stardust"], 0, "Order 66 is the programmed command that starts the Jedi purge."],
    ["force", "easy", "Galactic Republic", "Which democratic government precedes the Galactic Empire?", ["Galactic Republic", "First Order", "Confederacy of Independent Systems", "Shadow Collective"], 0, "The Galactic Republic falls as Palpatine declares the Empire."],
    ["force", "easy", "Galactic Empire", "Which authoritarian regime is formed by Palpatine after the Clone Wars?", ["Galactic Empire", "New Republic", "Resistance", "Jedi Order"], 0, "Palpatine reorganizes the Republic into the Galactic Empire."],
    ["force", "easy", "Alliance to Restore the Republic", "Which rebel movement fights the Galactic Empire in the original trilogy?", ["Rebel Alliance", "First Order", "Trade Federation", "Techno Union"], 0, "The Rebel Alliance seeks to restore freedom and defeat the Empire."],
    ["force", "easy", "Resistance", "Which military group led by Leia opposes the First Order?", ["Resistance", "Separatist Alliance", "Imperial Remnant", "Nightsisters"], 0, "The Resistance fights the First Order when the New Republic cannot contain it."],
    ["force", "easy", "First Order", "Which faction rises from Imperial remnants during the sequel era?", ["First Order", "Rebel Alliance", "Jedi Order", "Galactic Senate"], 0, "The First Order grows from Imperial remnants and threatens the New Republic."],
    ["force", "medium", "Mandalorian", "Which warrior culture values beskar armor, foundlings, and clan identity?", ["Mandalorians", "Kaminoans", "Ewoks", "Neimoidians"], 0, "Mandalorian identity centers on clans, armor, creed, and warrior tradition."],
    ["force", "medium", "Nightsisters", "Which Dathomirian Force tradition is associated with magick and witch clans?", ["Nightsisters", "Jedi Sentinels", "Sith Eternal", "Guardians of the Whills"], 0, "The Nightsisters are Dathomirian witches with their own Force-related practices."],
    ["force", "medium", "Inquisitorius", "Which Imperial group hunts surviving Jedi after Order 66?", ["Inquisitorius", "Rebel Pathfinders", "Red Guard", "Pyke Syndicate"], 0, "The Inquisitorius uses dark side agents to hunt Jedi survivors."],
    ["force", "medium", "Holocron", "What artifact stores Jedi or Sith teachings in crystalline form?", ["Holocron", "Wayfinder", "Comlink", "Datapad"], 0, "Holocrons preserve Force knowledge and often require Force sensitivity to access."],
    ["force", "medium", "Force ghost", "What can some Jedi become after death through special Force training?", ["Force ghosts", "Clone shadows", "Holograms", "Nightbrothers"], 0, "Certain Jedi retain identity after death and appear as Force spirits."],
    ["force", "hard", "Midi-chlorian", "What microscopic life forms are connected to a being's ability to hear the will of the Force?", ["Midi-chlorians", "Purrgil", "Kouhuns", "Mynocks"], 0, "Midi-chlorians are described as symbiotic life forms tied to Force sensitivity."],

    ["species", "easy", "R2-D2", "Which astromech droid carries Leia's message and the Death Star plans?", ["R2-D2", "C-3PO", "BB-9E", "K-2SO"], 0, "R2-D2 transports Leia's message and the plans that guide the Rebellion."],
    ["species", "easy", "C-3PO", "Which protocol droid is fluent in millions of forms of communication?", ["C-3PO", "R5-D4", "IG-11", "L3-37"], 0, "C-3PO is a protocol droid built for etiquette, translation, and communication."],
    ["species", "easy", "BB-8", "Which rolling astromech droid belongs to Poe Dameron?", ["BB-8", "D-O", "Chopper", "R4-P17"], 0, "BB-8 carries Poe's map fragment and aids the Resistance."],
    ["species", "easy", "Chewbacca", "Which Wookiee is Han Solo's longtime co-pilot?", ["Chewbacca", "Tarfful", "Black Krrsantan", "Zaalbar"], 0, "Chewbacca is Han's loyal friend and co-pilot aboard the Falcon."],
    ["species", "easy", "Wookiee", "Which tall, fur-covered species comes from Kashyyyk?", ["Wookiees", "Ewoks", "Lasats", "Gungans"], 0, "Wookiees are native to Kashyyyk and known for strength and loyalty."],
    ["species", "easy", "Ewok", "Which small forest species helps defeat the Empire on Endor?", ["Ewoks", "Jawas", "Ugnaughts", "Porgs"], 0, "Ewoks ally with the Rebels during the Battle of Endor."],
    ["species", "easy", "Jawa", "Which hooded scavengers sell droids from sandcrawlers on Tatooine?", ["Jawas", "Tuskens", "Geonosians", "Toydarians"], 0, "Jawas are Tatooine scavengers who trade in recovered technology."],
    ["species", "easy", "Tusken Raider", "Which desert people of Tatooine are also called Sand People?", ["Tusken Raiders", "Nikto", "Pykes", "Weequay"], 0, "Tusken Raiders are indigenous desert inhabitants of Tatooine."],
    ["species", "easy", "Hutt", "Which sluglike species includes the crime lord Jabba?", ["Hutt", "Rodian", "Quarren", "Aqualish"], 0, "Jabba is a Hutt, a species often tied to criminal cartels in the saga."],
    ["species", "medium", "Rodian", "Which green-skinned species includes Greedo?", ["Rodian", "Duros", "Ithorian", "Neimoidian"], 0, "Greedo is a Rodian bounty hunter in Mos Eisley."],
    ["species", "medium", "Twi'lek", "Which species is known for head-tails called lekku?", ["Twi'lek", "Togruta", "Mirialan", "Pantoran"], 0, "Twi'leks have lekku and are native to Ryloth."],
    ["species", "medium", "Mon Calamari", "Which aquatic species designs many Rebel capital ships and includes Admiral Ackbar?", ["Mon Calamari", "Quarren", "Kaminoan", "Gungan"], 0, "Mon Calamari shipyards produce major Rebel and New Republic vessels."],
    ["species", "hard", "Chiss", "Which blue-skinned, red-eyed species includes Grand Admiral Thrawn?", ["Chiss", "Pantoran", "Duros", "Sullustan"], 0, "Thrawn is a Chiss from the Unknown Regions."],
    ["species", "medium", "Togruta", "Which species includes Ahsoka Tano and has montrals and lekku?", ["Togruta", "Twi'lek", "Zabrak", "Mirialan"], 0, "Ahsoka is a Togruta, recognizable by montrals and striped lekku."],
    ["species", "medium", "Kaminoan", "Which tall, long-necked species creates the Republic's clone army?", ["Kaminoans", "Geonosians", "Muun", "Pau'ans"], 0, "Kaminoans are expert cloners on Kamino."],
    ["species", "easy", "Gungan", "Which amphibious Naboo species includes Jar Jar Binks?", ["Gungans", "Ewoks", "Selkath", "Karkarodons"], 0, "Gungans live on Naboo and maintain underwater cities."],
    ["species", "easy", "Porg", "Which small seabirds live around Luke's island on Ahch-To?", ["Porgs", "Mynocks", "Convorees", "Boglings"], 0, "Porgs are native to Ahch-To's islands."],
    ["species", "easy", "Tauntaun", "Which snow creature is used as a mount by Rebels on Hoth?", ["Tauntaun", "Bantha", "Rancor", "Varactyl"], 0, "Tauntauns help Rebels patrol the icy terrain of Hoth."],
    ["species", "easy", "Bantha", "Which large, shaggy mount is associated with Tatooine and Tusken Raiders?", ["Bantha", "Dewback", "Reek", "Blurrg"], 0, "Banthas are commonly seen with Tusken Raiders on Tatooine."],
    ["species", "medium", "Sarlacc", "Which pit-dwelling creature threatens prisoners at the Great Pit of Carkoon?", ["Sarlacc", "Rancor", "Krayt dragon", "Zillo Beast"], 0, "The Sarlacc lives in the Great Pit of Carkoon and nearly consumes several heroes."],
  ];

  window.HOLOCRON_CATEGORIES = categories;
  window.HOLOCRON_QUESTIONS = rows.map((row, index) => ({
    id: `Q${String(index + 1).padStart(3, "0")}`,
    category: row[0],
    categoryLabel: categories[row[0]],
    difficulty: row[1],
    wikiTitle: row[2],
    prompt: row[3],
    choices: row[4],
    answer: row[5],
    explanation: row[6]
  }));
})();
